var md5 = require('md5');

/**
	Generated by sails-inverse-model
	Date:Wed Dec 04 2019 00:09:02 GMT+0700 (Indochina Time)
*/

module.exports = {
    attributes: {
        createdAt: false,
        updatedAt: false,
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            autoIncrement: true,
        },
        username: {
            type: "string",
            columnType: "varchar",
            maxLength: 45
        },
        password: {
            type: "string",
            columnType: "varchar",
            maxLength: 45
        },
        name: {
            type: "string",
            columnType: "varchar",
            maxLength: 45
        },
        type: {
            type: "number",
            columnType: "int",
            isInteger: true
        }
    },
    beforeCreate: function (values, cb) {
        values.password = md5(values.password);
        cb();
    }
};