/**
	Generated by sails-inverse-model
	Date:Wed Dec 04 2019 03:04:13 GMT+0700 (Indochina Time)
*/

module.exports = {
    attributes: {
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        rank: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        content: {
            type: "string",
            columnType: "varchar",
            maxLength: 100
        },
        id_account: {
            type: "number",
            columnType: "int",
            isInteger: true
        }
    }
};