/**
	Generated by sails-inverse-model
	Date:Wed Dec 04 2019 03:04:13 GMT+0700 (Indochina Time)
*/

module.exports = {
    primaryKey: 'id_account',
    attributes: {
        id_account: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        id_test: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
        grade: {
            type: "number",
            columnType: "int",
            isInteger: true
        }
    }
};