/**
	Generated by sails-inverse-model
	Date:Wed Dec 04 2019 03:04:13 GMT+0700 (Indochina Time)
*/

module.exports = {
    tableName: 'the_sentence_question',
    attributes: {
        createdAt: false,
        updatedAt: false,
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        content: {
            type: "string",
            columnType: "varchar",
            maxLength: 100
        },
        answer: {
            type: "string",
            columnType: "varchar",
            maxLength: 45
        },
        the_test_and_the_sentence: {
            collection: 'thetestandthesentencequestion',
            via: 'id_question'
        },
    }
};