/**
	Generated by sails-inverse-model
	Date:Wed Dec 04 2019 03:04:13 GMT+0700 (Indochina Time)
*/

module.exports = {
    tableName: 'the_test_and_the_choice_question',
    attributes: {
        createdAt: false,
        updatedAt: false,
        id_test: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        id_question: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        id_test: {
            model: 'thetest'
        },
        id_question:{
            model: "thechoicequestion"
        }
    }

};