/**
	Generated by sails-inverse-model
	Date:Wed Dec 04 2019 00:09:02 GMT+0700 (Indochina Time)
*/

module.exports = {
    tableName: 'the_test',
    attributes: {
        createdAt: false,
        updatedAt: false,
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        type: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
        id_class: {
            type: "number",
            columnType: "int",
            isInteger: true
        },

        // Add a reference to  the choice question
        the_test_and_the_choice: {
            collection: 'thetestandthechoicequestion',
            via: 'id_test'
        },

        the_choice_question: {
            collection: 'thechoicequestion',
            via: 'the_test'
        }
    }
};